version: '3.0'
volumes:
  go-pkg:

services:
  pingr:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
    environment:
      DEV: |-
        true
      SMTP_HOST: "smtp.gmail.com"
      SMTP_USERNAME: "pingrman@gmail.com"
      SMTP_PASSWORD: "2KPy8WJr2uLC46g"
    ports:
    - "8080:8080"
    volumes:
      - go-pkg:/go/pkg
      - .:/go/src/pingr

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui.dev
      args:
        UID: ${UID}
    environment:
      DEV: |-
        true
    ports:
      - "8081:8081"
#      - "8080:8080"
    volumes:
      - ./ui:/ui