version: '3.0'
volumes:
  gopkg:

services:
  pingr:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
    environment:
      DEV: |-
        true
      SMTP_HOST: "smtp.gmail.com"
      SMTP_USERNAME: "pingrman@gmail.com"
      SMTP_PASSWORD: "2KPy8WJr2uLC46g"
    ports:
    - "8080:8080"
    volumes:
      - gopkg:/go/pkg
      - .:/go/src/pingr
