version: '3.0'
volumes:
  go-pkg:

services:
  pingr-built:
    image: modfin/pingrd:latest
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647
    environment:
      HTTP_PORT: 8080
      BASE_URL: "http://localhost:8080"
      BASIC_AUTH_USER: "admin"
      BASIC_AUTH_PASS: "123abc"
      SMTP_HOST: "smtp.example.com"
      SMTP_USERNAME: "example@smtp-server.com"
      SMTP_PASSWORD: "smtpPassword"
      AES_KEY: "6368616e676520746869732070617373776f726420746f206120736563726574" ## Generate using 'openssl rand -hex 32'
    ports:
      - "8080:8080"